In [32]:
import pandas as pd
import numpy as np
from geopy.distance import geodesic
import folium

In [33]:
pas = pd.read_csv("data/01-SecretariadeMovilidad/PASAJEROS_ARANJUEZ_SANTA_CRUZ.csv", encoding="latin-1", sep=";")
pas.columns = pas.columns.str.lower()

In [34]:
tra = pd.read_csv("data/01-SecretariadeMovilidad/TRANSPORTES_ARANJUEZ_SANTA_CRUZ.csv", encoding="latin-1", sep=";")
tra.columns = tra.columns.str.lower()

In [35]:
# Atributo esarchivolinea, puede ser interesante

columnas_drop = ["nombrearchivo", "idempresa", "idpersona", "esarchivolinea", "diferenciadepasajeros", "ordenregistro",
       "tipocarga", "idpersonausuario", "archivofirmado","fechavencimientofirma", "indfechacreacion", "fecha_carga",
       "ultimoestadopuertas", "presentocambioenpuertas", "ordenregistro","ipmaquina", "placavehiculo", "codigo_id",
       "id_tipo_ruta", "nombre_ruta", "secuenciarecorrido", "cantidadregistros", "ultimafecharegistro"]

tra = tra.drop(columnas_drop, axis=1)

In [36]:
tra["ultimalatitudregistro"] = pd.to_numeric(tra["ultimalatitudregistro"].str.replace(",", "."))
tra["ultimalongitudregistro"] = pd.to_numeric(tra["ultimalongitudregistro"].str.replace(",", "."))

In [37]:
tra["codigo_ruta"].unique()

array(['024', '041 D', '023', '022', '042', '041 I '], dtype=object)

In [103]:
example1 = tra.groupby(("codigo_ruta")).get_group(("022")).sort_values(by=["ultimalongitudregistro","ultimalatitudregistro"])
coords1 = [coord[::-1] for coord in example1[["ultimalongitudregistro", "ultimalatitudregistro"]].values.tolist()]

example2 = tra.groupby(("codigo_ruta")).get_group(("042")).sort_values(by=["ultimalongitudregistro","ultimalatitudregistro"])
coords2 = [coord[::-1] for coord in example2[["ultimalongitudregistro", "ultimalatitudregistro"]].values.tolist()]

In [104]:
# Create a map object centered at a specific location
m = folium.Map(location=coords1[0], zoom_start=13)

# for coord in coords1:
#     folium.Marker(
#         location = coord,
#         icon=folium.Icon(color="blue", icon="info-sign"),
#         tooltip=""
#     ).add_to(m)

for coord in coords2:
    folium.Marker(
        location = coord,
        icon=folium.Icon(color="red", icon="info-sign"),
        tooltip=""
    ).add_to(m)

m.save("mapa.html")

In [110]:
tra

,empresa_transporte,idvehiculo,idruta,codigo_ruta,min_registros_ruta,longitudruta,tipo_ruta,fechainiciodespacho,fechafindespacho,recorridofinalizado,fecha_creacion,cantpasajerossuben,cantpasajerosbajan,ultimalongitudregistro,ultimalatitudregistro,distanciarecorrido,recorridoincumplido,distanciaincumplidainicio,distanciaincumplidafin
0,TRANSPORTES ARANJUEZ SANTA CRUZ,2595,803,024,33,"8026,96",Directa no centro,23/09/25 21:55:09,23/09/25 22:54:16,N,23/09/2025 21:55:09,0,0,-75.564079,6.288920,3131,S,"2289,21","182,73"
1,TRANSPORTES ARANJUEZ SANTA CRUZ,5265,803,024,33,"8026,96",Directa no centro,23/09/25 21:41:04,23/09/25 21:55:55,S,23/09/2025 21:41:04,1,14,-75.562950,6.290425,3141,S,"2085,51","192,06"
2,TRANSPORTES ARANJUEZ SANTA CRUZ,5268,529,041 D,70,"16776,67",Directa centro,23/09/25 21:40:31,23/09/25 22:47:11,S,23/09/2025 21:40:31,4,3,-75.551727,6.287636,13179,S,"216,73","480,45"
3,TRANSPORTES ARANJUEZ SANTA CRUZ,5222,529,041 D,70,"16776,67",Directa centro,23/09/25 21:20:32,23/09/25 22:32:46,S,23/09/2025 21:20:32,4,3,-75.552109,6.287522,13399,S,"254,01","454,19"
4,TRANSPORTES ARANJUEZ SANTA CRUZ,5271,803,024,33,"8026,96",Directa no centro,23/09/25 21:12:57,23/09/25 21:30:28,S,23/09/2025 21:12:57,4,19,-75.564247,6.288287,3332,S,"2350,1","124,81"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1926,TRANSPORTES ARANJUEZ SANTA CRUZ,5290,526,023,75,"18004,93",Directa centro,21/09/25 04:40:32,21/09/25 06:03:54,S,21/09/2025 04:40:32,11,12,-75.552368,6.304451,17437,S,0,"46,74"
1927,TRANSPORTES ARANJUEZ SANTA CRUZ,6892,525,022,69,"16621,12",Directa centro,21/09/25 04:37:31,21/09/25 05:52:00,S,21/09/2025 04:37:31,8,8,-75.549599,6.292368,16630,S,0,"188,77"
1928,TRANSPORTES ARANJUEZ SANTA CRUZ,7010,526,023,75,"18004,93",Directa centro,21/09/25 04:28:55,21/09/25 05:43:30,S,21/09/2025 04:28:55,3,3,-75.552132,6.304982,17217,S,"68,58","51,16"
1929,TRANSPORTES ARANJUEZ SANTA CRUZ,5272,525,022,69,"16621,12",Directa centro,21/09/25 04:23:23,21/09/25 05:18:48,S,21/09/2025 04:23:23,3,4,-75.548569,6.291197,16043,S,"176,82","155,53"
1930,TRANSPORTES ARANJUEZ SANTA CRUZ,5233,526,023,75,"18004,93",Directa centro,21/09/25 04:20:35,21/09/25 05:31:45,S,21/09/2025 04:20:35,9,9,-75.552658,6.304400,16251,S,"24,25","199,13"

In [109]:
# Hallar la ruta con menor varianza en la cantidad de buses
ruta_min = tra.groupby(by="codigo_ruta")["idvehiculo"].nunique().nsmallest()

ruta_min

codigo_ruta
042       19
023       26
022       27
041 D     31
041 I     33
Name: idvehiculo, dtype: int64

In [45]:
columnas_drop = ["empresa", "nombrearchivo"]
pas = pas.drop(columnas_drop, axis=1)

In [47]:
pas

,codigoruta,rutaot,descripcion,fecha,horaregistro,longitud,latitud,velocidad,passuben,pasbajan,consecutivo
0,121275,041 I,ARANJUEZ GUADALUPE,22/09/2025,06:33:39,"-75,546005","6,286640",17,1,0,9
1,121275,041 I,ARANJUEZ GUADALUPE,22/09/2025,06:34:01,"-75,545937","6,287443",14,1,0,11
2,121275,041 I,ARANJUEZ GUADALUPE,22/09/2025,06:34:31,"-75,545860","6,287635",0,4,0,13
3,121275,041 I,ARANJUEZ GUADALUPE,22/09/2025,06:34:52,"-75,546577","6,287738",17,1,0,14
4,121275,041 I,ARANJUEZ GUADALUPE,22/09/2025,06:35:15,"-75,546684","6,287658",6,2,0,16
...,...,...,...,...,...,...,...,...,...,...,...
57898,121265,041 D,ARANJUEZ ANILLO,23/09/2025,20:20:08,"-75,552704","6,284558",6,0,1,216
57899,121265,041 D,ARANJUEZ ANILLO,23/09/2025,20:21:11,"-75,552620","6,286547",0,0,1,219
57900,121265,041 D,ARANJUEZ ANILLO,23/09/2025,20:21:49,"-75,552673","6,287265",12,0,1,221
57901,121265,041 D,ARANJUEZ ANILLO,23/09/2025,20:22:13,"-75,552635","6,287332",0,0,4,223
57902,121265,041 D,ARANJUEZ ANILLO,23/09/2025,20:23:11,"-75,552307","6,287422",0,0,2,225

In [90]:
pas["longitud"] = pd.to_numeric(pas["longitud"].str.replace(",", "."))
pas["latitud"] = pd.to_numeric(pas["latitud"].str.replace(",", "."))

In [91]:
pas.sort_values(by=["rutaot","horaregistro", "fecha","latitud"], inplace=True)

In [92]:
pas["rutaot"].unique()

array(['022', '023', '024', '041 D', '041 I ', '042'], dtype=object)

In [106]:
pas_rutaot1 = pas.groupby(("rutaot")).get_group(("042")).sort_values(by=["fecha","horaregistro"])

coords1 = [coord[::-1] for coord in pas_rutaot1[:1000][["longitud", "latitud"]].values.tolist()]

In [107]:
# Create a map object centered at a specific location
m = folium.Map(location=coords1[0], zoom_start=13)

for coord in coords1:
    folium.Marker(
        location = coord,
        icon=folium.Icon(color="blue", icon="info-sign"),
        tooltip="042"
    ).add_to(m)

# for coord in coords2:
#     folium.Marker(
#         location = coord,
#         icon=folium.Icon(color="red", icon="info-sign"),
#         tooltip="041 I"
#     ).add_to(m)

m.save("mapa.html")